import numpy as np

mat1 = np.array([[12,23,22],[5,87,34],[44,77,3]])
mat2 = np.array([[12,32,22],[5,78,43],[44,77,3]])
print('FIRST MATRIX IS:\n', mat1)
print('SECOND MATRIX IS:\n', mat2)
print('ADDITION:')
print(np.add(mat1,mat2))
print('SUBTRACTION:')
print(np.subtract(mat1,mat2))
print('DIVISION:')
print(np.divide(mat1,mat2))
print('MULTIPLICATION:')
print(np.multiply(mat1,mat2))
print('DOT PRODUCT:')
print(np.dot(mat1,mat2))
print('SQUARE ROOT:')
print(np.sqrt(mat1))
print('SUMMATION:')
print(np.sum(mat1))
print('TRANSPOSE USING "T" :')
print(mat1.T)
print('TRANSPOSE USING TRANSPOSE FUNCTION:')
print(np.transpose(mat1))

